### ISSUE TITLE
return next key in lexicographic sort order

### ISSUE THREAD

**Issue by benoitc** [uwiger/sext#13]
Is there a way to return the next key in lexical order based on a key encoded with sext?

Ie i have keys like <<"a">>, {<<"a">>,1},   {<<"a">>,1}, but would would like to jump from <<"a">> to <<"aa">> . Is this possible?

**Comment by benoitc** [comment]
sorry forgot to close the issue. doing it now

**Comment by richcarl** [comment]
@benoitc Failed to close this?

**Comment by benoitc** [comment]
apparently...
