### ISSUE TITLE
rebar3 do not compile sext

### ISSUE THREAD

**Issue by contented** [uwiger/sext#20]
Hello, Ulf!

Rebar3 do not compile sext. 
The reasons are: lack of src dir and not working C interface.

**Comment by uwiger** [comment]
Could you describe what you're doing to cause this problem?
I've had no problem compiling sext with rebar3 (using OTP 18.3.1)

**Comment by contented** [comment]
I have rebar 3.1.0 on Erlang/OTP 17 Erts 6.4
I do:

**$** git clone git@github.com:uwiger/sext.git
**$** rebar3 compile
```
===> Verifying dependencies...
===> Fetching edown ({git,"git://github.com/uwiger/edown.git","HEAD"})
===> WARNING: It is recommended to use {branch, Name}, {tag, Tag} or {ref, Ref}, otherwise updating the dep may not work as expected.
===> Compiling edown
===> Compiling sext
```
**$** ls 

> Here I have problem N1 - C code doesn't compile. (No priv dir)

```
LICENSE		README.md	examples	rebar.lock	vsn.mk
Makefile	_build		rebar		src
NOTICE		doc		rebar.config	test
```
**$** ls _build/default/lib/sext/ebin/

> Here I have problem N2 - Rebar3 doesn't see the src dir.

`sext.app	tt_proto.beam`
