### ISSUE TITLE
Can't depend on sext through Hex

### ISSUE THREAD

**Issue by cs-victor-nascimento** [uwiger/sext#32]
Hello!

I was trying to use LASP dependency from Hex but its dependency on `sext` is breaking the build. Upon further investigation it seems rebar is getting lost with current `rebar.config.script`.

I don't understand rebar configuration but it breaks with reason `badmatch` and stacktrace `[{erl_eval,expr,3,[]}]` (I know it is not very helpful, but I am posting here just in case).

To reproduce just create a new mix project, add sext as a dependency and do `mix deps.get`.

Thanks!

**Comment by uwiger** [comment]
Hi!

This bug in `rebar.config.script` was actually fixed long ago, but I hadn't pushed a new version to hex. Please try the 1.4.1 version up there now.

**Comment by cs-victor-nascimento** [comment]
Thanks! It worked!

I am using the following configuration (just for reference):

```elixir
      {:sext, "~> 1.4", manager: :rebar},
      {:edown, "~> 0.8"}
```
