### ISSUE TITLE
Big ints don't sort properly

### ISSUE THREAD

**Issue by reiddraper** [uwiger/sext#5]
Riak uses `sext` for secondary indexes to create binary keys for leveldb. A user noticed that some integer 2i queries were not returning results when they were expected to. We seem to have narrowed the issue down to `sext`. Here's an example, in an erlang shell:

```
76> TA = 1000000000000.
1000000000000
77> TB = 2000000000000.
2000000000000
78> TA < TB.
true
79> sext:encode(TA) < sext:encode(TB).
false
```

You can provoke this bug by using [this patch](https://gist.github.com/reiddraper/ea3a5d9145c10e635550) to the EQC tests. h/t to @seancribbs and @vagabond for helping track this down.

**Comment by benoitc** [comment]
shouldn't it be closed?

**Comment by uwiger** [comment]
Indeed. Thanks.
